import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export const AdminLayout = ({ pageTitle, userInfo, navigationItems, children, showBreadcrumbs = true, breadcrumbs = [], headerActions, defaultCollapsed = false, }) => {
    const [sidebarCollapsed, setSidebarCollapsed] = useState(defaultCollapsed);
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("div", { className: `fixed inset-y-0 left-0 z-50 w-64 bg-white shadow-lg transform transition-transform duration-300 ease-in-out ${sidebarCollapsed ? '-translate-x-full lg:translate-x-0 lg:w-16' : 'translate-x-0'}`, children: _jsx(AdminSidebar, { items: navigationItems, collapsed: sidebarCollapsed, onToggle: () => setSidebarCollapsed(!sidebarCollapsed) }) }), _jsxs("div", { className: `transition-all duration-300 ease-in-out ${sidebarCollapsed ? 'lg:ml-16' : 'lg:ml-64'}`, children: [_jsx(AdminHeader, { pageTitle: pageTitle, userInfo: userInfo, showBreadcrumbs: showBreadcrumbs, breadcrumbs: breadcrumbs, headerActions: headerActions, onMenuToggle: () => setSidebarCollapsed(!sidebarCollapsed) }), _jsx("main", { className: "p-6", children: children })] }), !sidebarCollapsed && (_jsx("div", { className: "fixed inset-0 z-40 bg-black bg-opacity-50 lg:hidden", onClick: () => setSidebarCollapsed(true) }))] }));
};
const AdminHeader = ({ pageTitle, userInfo, showBreadcrumbs, breadcrumbs, headerActions, onMenuToggle, }) => {
    return (_jsx("header", { className: "bg-white shadow-sm border-b border-gray-200", children: _jsx("div", { className: "px-6 py-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("button", { onClick: onMenuToggle, className: "lg:hidden p-2 rounded-md text-gray-600 hover:text-gray-900 hover:bg-gray-100", children: _jsx("svg", { className: "w-6 h-6", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M4 6h16M4 12h16M4 18h16" }) }) }), _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-semibold text-gray-900", children: pageTitle }), showBreadcrumbs && breadcrumbs && breadcrumbs.length > 0 && (_jsx("nav", { className: "flex", "aria-label": "Breadcrumb", children: _jsx("ol", { className: "flex items-center space-x-2 text-sm text-gray-500", children: breadcrumbs.map((crumb, index) => (_jsxs("li", { className: "flex items-center", children: [index > 0 && (_jsx("svg", { className: "w-4 h-4 mx-2", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z", clipRule: "evenodd" }) })), crumb.href ? (_jsx("a", { href: crumb.href, className: "hover:text-gray-700", children: crumb.label })) : (_jsx("span", { children: crumb.label }))] }, index))) }) }))] })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [headerActions && (_jsx("div", { className: "flex items-center space-x-2", children: headerActions })), userInfo && (_jsxs("div", { className: "flex items-center space-x-3", children: [_jsxs("div", { className: "text-right", children: [_jsx("p", { className: "text-sm font-medium text-gray-900", children: userInfo.name }), userInfo.email && (_jsx("p", { className: "text-xs text-gray-500", children: userInfo.email }))] }), _jsx("div", { className: "w-8 h-8 bg-gray-300 rounded-full flex items-center justify-center", children: userInfo.avatar ? (_jsx("img", { src: userInfo.avatar, alt: userInfo.name, className: "w-8 h-8 rounded-full" })) : (_jsx("span", { className: "text-sm font-medium text-gray-700", children: userInfo.name.charAt(0).toUpperCase() })) })] }))] })] }) }) }));
};
const AdminSidebar = ({ items, collapsed, onToggle }) => {
    return (_jsxs("div", { className: "flex flex-col h-full", children: [_jsx("div", { className: "flex items-center justify-center h-16 px-4 border-b border-gray-200", children: _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("div", { className: "w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold text-sm", children: "A" }) }), !collapsed && (_jsx("span", { className: "font-semibold text-gray-900", children: "Admin" }))] }) }), _jsx("nav", { className: "flex-1 px-4 py-4 space-y-1 overflow-y-auto", children: items.map((item) => (_jsxs("div", { children: [_jsxs("a", { href: item.href || '#', className: `flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors ${collapsed ? 'justify-center' : 'justify-between'} ${item.href ? 'text-gray-700 hover:bg-gray-100 hover:text-gray-900' : 'text-gray-900 bg-gray-100'}`, title: collapsed ? item.label : undefined, children: [_jsxs("div", { className: "flex items-center space-x-3", children: [item.icon && (_jsx("span", { className: "text-lg", children: item.icon })), !collapsed && _jsx("span", { children: item.label })] }), !collapsed && item.badge && (_jsx("span", { className: "inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800", children: item.badge }))] }), !collapsed && item.children && item.children.length > 0 && (_jsx("div", { className: "ml-6 mt-1 space-y-1", children: item.children.map((child) => (_jsx("a", { href: child.href, className: "block px-3 py-2 text-sm text-gray-600 rounded-md hover:bg-gray-100 hover:text-gray-900", children: child.label }, child.id))) }))] }, item.id))) }), _jsx("div", { className: "p-4 border-t border-gray-200", children: _jsxs("button", { onClick: onToggle, className: "w-full flex items-center justify-center px-3 py-2 text-sm font-medium text-gray-700 rounded-md hover:bg-gray-100", title: collapsed ? 'Expand sidebar' : 'Collapse sidebar', children: [_jsx("svg", { className: `w-5 h-5 transition-transform ${collapsed ? 'rotate-180' : ''}`, fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M11 19l-7-7 7-7m8 14l-7-7 7-7" }) }), !collapsed && _jsx("span", { className: "ml-2", children: "Collapse" })] }) })] }));
};
